jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restore Package Cache
          key: dependencies-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          name: Save Package Cache
          key: dependencies-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Build
          command: yarn build
  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restore Package Cache
          key: dependencies-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Lint
          command: yarn lint

  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          name: Restore Package Cache
          key: dependencies-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: yarn test
  build_docker_image:
    environment:
      IMAGE_NAME: renatomorenocz/circleci-101
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .

workflows:
  version: 2
  default:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - build_docker_image:
          requires:
            - lint
            - test
